.libPaths(c("/Users/rubenmorevalencia/Desktop/SYJ/TraceExplorer.DSNeuralRNAS/_release/lib_rc_0.10.2", .libPaths()))
library(TraceExplorer.DSNeuralRNAS, lib.loc = "/Users/rubenmorevalencia/Desktop/SYJ/TraceExplorer.DSNeuralRNAS/_release/lib_rc_0.10.2")
stopifnot(as.character(packageVersion('TraceExplorer.DSNeuralRNAS', lib.loc = "/Users/rubenmorevalencia/Desktop/SYJ/TraceExplorer.DSNeuralRNAS/_release/lib_rc_0.10.2")) == "0.10.2")
tr <- te_demo_mlp_trace(12)
stopifnot(inherits(tr, 'te_trace'))
stopifnot(nrow(te_trace_data(tr)) >= 2L)
stopifnot(all(te_validate_trace(te_trace_data(tr))$status == 'PASS'))
sp <- te_learning_space(tr)
stopifnot(is.data.frame(sp), nrow(sp) >= 2L)
ev <- te_evidence_stack(tr)
stopifnot(inherits(ev, 'te_evidence_stack'))
stopifnot(all(te_validate_evidence_stack(ev)$status == 'PASS'))
app <- system.file('shiny', 'app', 'app.R', package = 'TraceExplorer.DSNeuralRNAS')
stopifnot(nzchar(app), file.exists(app))
parse(file = app)
if (requireNamespace('DSNeuralRNAS.FormalSpec', quietly = TRUE)) {
  fs <- te_run_formalspec(tr)
  stopifnot(inherits(fs, 'te_formalspec_analysis'))
  stopifnot(all(te_validate_formalspec_analysis(fs)$status == 'PASS'))
}
cat('SMOKE PASS\n')
